# Generated by Django 4.2.3 on 2023-08-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_basket_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('number', models.CharField(max_length=15)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.basket')),
            ],
        ),
    ]
