# Generated by Django 4.2.3 on 2023-08-06 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
